import type { IconType } from "react-icons";
import {
  FaGithub,
  FaLinkedin,
  FaJava,
  FaAws,
  FaRegEnvelope,
  FaRegFilePdf,
  FaCode,
  FaLock,
  FaChartBar,
  FaFileExcel,
  FaPaypal,
  FaCoffee,
  FaGraduationCap,
  FaMapMarkerAlt,
  FaStar,
  FaArrowRight,
  FaArrowLeft,
  FaExternalLinkAlt,
  FaChevronDown,
  FaCopy,
  FaCheck,
  FaQrcode,
  FaSyncAlt,
  FaHeart,
  FaDatabase,
  FaLink,
  FaRegClock,
} from "react-icons/fa";
import {
  SiLeetcode,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiRedis,
  SiPrisma,
  SiSocketdotio,
  SiReactquery,
  SiJavascript,
  SiExpress,
  SiMongodb,
  SiMysql,
  SiPython,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiBootstrap,
  SiDocker,
  SiGit,
  SiNginx,
  SiGithubactions,
  SiCloudinary,
  SiFigma,
  SiCanvas,
  SiJsonwebtokens,
} from "react-icons/si";
const icons: Record<string, IconType> = {
  github: FaGithub,
  linkedin: FaLinkedin,
  leetcode: SiLeetcode,
  typescript: SiTypescript,
  react: SiReact,
  nextjs: SiNextdotjs,
  nodejs: SiNodedotjs,
  postgresql: SiPostgresql,
  redis: SiRedis,
  prisma: SiPrisma,
  socketio: SiSocketdotio,
  query: SiReactquery,
  javascript: SiJavascript,
  express: SiExpress,
  mongodb: SiMongodb,
  mysql: SiMysql,
  java: FaJava,
  python: SiPython,
  html: SiHtml5,
  css: SiCss,
  tailwind: SiTailwindcss,
  bootstrap: SiBootstrap,
  docker: SiDocker,
  aws: FaAws,
  git: SiGit,
  nginx: SiNginx,
  githubactions: SiGithubactions,
  cloudinary: SiCloudinary,
  figma: SiFigma,
  canva: SiCanvas,
  jwt: SiJsonwebtokens,
  code: FaCode,
  lock: FaLock,
  chart: FaChartBar,
  sheet: FaFileExcel,
  email: FaRegEnvelope,
  resume: FaRegFilePdf,
  paypal: FaPaypal,
  coffee: FaCoffee,
  education: FaGraduationCap,
  location: FaMapMarkerAlt,
  star: FaStar,
  right: FaArrowRight,
  left: FaArrowLeft,
  external: FaExternalLinkAlt,
  chevron: FaChevronDown,
  copy: FaCopy,
  check: FaCheck,
  qr: FaQrcode,
  refresh: FaSyncAlt,
  heart: FaHeart,
  database: FaDatabase,
  link: FaLink,
  clock: FaRegClock,
};
export default function Icon({
  name,
  className,
  colored = false,
}: {
  name: string;
  className?: string;
  colored?: boolean;
}) {
  if (name === "leetcode" && colored) {
    return (
      <svg viewBox="0 0 24 24" width="1em" height="1em" aria-hidden="true" className={className} fill="none" strokeWidth="2.7" strokeLinecap="round" strokeLinejoin="round">
        <path d="M13.5 1.5 4.3 11.4" stroke="#60666d" />
        <path d="m17.9 9.4-3.5-2.8c-1.8-1.5-4.8-1.3-6.3.3l-3.8 4.5c-1.7 1.8-1.5 4.3.2 6l4.3 4.2c1.7 1.6 4.4 1.6 6.2-.1l2.4-2.4" stroke="#ffa116" />
        <path d="M10.6 14.2h10.2" stroke="#92999f" />
      </svg>
    );
  }
  const Component = icons[name] || FaCode;
  return <Component aria-hidden="true" className={className} />;
}
